name: zkPerf CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build
      - run: nix flake check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test -p zkperf-witness -p zkperf-macros -p cargo-zkperf
      - run: cargo fmt -- --check
      - run: cargo clippy -p zkperf-witness -p zkperf-macros -p cargo-zkperf -- -D warnings
